# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Bingo | zhrbin
subtitle: '随笔行舟,记录分享'
description: '记录生活&分享知识'
keywords: Linux,建站,V2Ray
author: Liaozhebin
language:  zh-CN #zh-Customize #zh-CN
timezone: 'Asia/Shanghai'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next 

# Deployment
## Docs: https://hexo.io/docs/deployment.html

# deploy:
#   type: git
#   message: 

deploy:
  type: git
  repo: 
    coding: https://e.coding.net/liaozhebin/liaozhebin.coding.me.git  #https://bitbucket.org/JohnSmith/johnsmith.bitbucket.io
    github: https://github.com/Liaozhebin/liaozhebin.github.io #https://bitbucket.org/JohnSmith/johnsmith.bitbucket.io
  branch:
    coding: coding-pages
  message: 


# word & read time analyzied
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true

# 站点本地搜索
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
# Markdown

#Markdown-it config
#markdown: 'zero'
#markdown: 'default'
#markdown: 'commonmark'
# Markdown-it config
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-checkbox # 本行启用了 checkbox 插件
    - markdown-it-emoji # 如果你想在 md 中使用 emoji 表情的话，需要另外下载相关插件
  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: false
    permalinkClass: header-anchor
    permalinkSymbol: ^

# 通用站点地图
sitemap:
  path: sitemap.xml
# 百度站点地图
baidusitemap:
  path: baidusitemap.xml

#RSS订阅
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:
#nofollow: 减去出站follow参数链接
#depency：https://github.com/hexojs/hexo-filter-nofollow
nofollow:
  enable: true
  field: site
  exclude:
    - 'exclude1.com'
    - 'exclude2.com'

#back2top bottom，回到顶部按钮
moon_menu:
  back2top:
    enable: true
    icon: fa fa-chevron-up
    func: back2top
    order: -1
  back2bottom:
    enable: true
    icon: fa fa-chevron-down
    func: back2bottom
    order: -2

#豆瓣电影&图书
douban:
  user: 152817575
  builtin: false
  book:
    title: '我的图书 / My Books'
    quote: 'This is my book quote'
  movie:
    title: '我的电影 / My Moives'
    quote: 'This is my movie quote'
  # game:
  #   title: 'This is my game title'
  #   quote: 'This is my game quote'
  timeout: 10000
